=== 707sven/CFGS-DAM/Markup-Language-and-Information-Management-Systems/XML/Tema 10/tienda/tienda.dtd
<!ELEMENT tienda (producto+)>
<!ELEMENT producto (productoID, nombre, marca, precio, (edadRecomendada|pegi), categoria+, descuento)>
<!ELEMENT productoID (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT pegi (#PCDATA)>
<!ELEMENT edadRecomendada (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>

=== 707sven/CFGS-DAM/Markup-Language-and-Information-Management-Systems/XML/Tema 10/tienda/tienda_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd">

<tienda>
    <producto>
        <productoID>01</productoID>
        <nombre>Spiderman</nombre>
        <marca>Marvel Comics</marca>
        <precio>10</precio>
        <edadRecomendada>12</edadRecomendada>
        <categoria>Comic</categoria>
        <descuento>20</descuento>
    </producto>
</tienda>
