=== 707sven/CFGS-DAM/Markup-Language-and-Information-Management-Systems/XML/Tema 10/libro.dtd
<!-- Para decir cuantos elementos puede tener un elemento se pone detrás de la palabra:
    + -> 1 o más
    * -> 0 o más
    ? -> 0 o 1
-->
<!ELEMENT libros (libro*)>

<!-- Los elementos tienen que estar todos en orden
    Se declara los elementos que contiene el elemento libro
    Se puede decir que un atributo tiene varias variables (que pueda elegir entre uno u otro), con (atributo1|atributo2)-->
<!ELEMENT libro (titulo, (autor|autora)*, paginas, editorial, genero+)>

<!-- Para referenciar a un tipo de atributo, en este caso un id
    - Si el atributo es necesario: #REQUIRED
    - Si el atributo es opcional: #IMPLIED
El atributo por defecto tiene ese valor -> "valor"
-->
<!ATTLIST libro libroID CDATA #REQUIRED>
<!ATTLIST libro ISBN CDATA "1000">

<!-- Se usa el #PCDATA para referenciar a que el elemento contiene una cadena de texto-->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT autora (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== 707sven/CFGS-DAM/Markup-Language-and-Information-Management-Systems/XML/Tema 10/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilos.css" type="text/css"?>

<!DOCTYPE libros SYSTEM "libro.dtd"> <!-- Declaración de libros -->

<libros>
    <libro libroID="1" ISBN="12345">
        <titulo>Los Pilares de la Tierra</titulo>
        <autor>Ken Follet</autor>
        <paginas>10000</paginas>
        <editorial>Planeta</editorial>
        <genero>Histórico</genero>
        <genero>Aventuras</genero>
    </libro>
    <libro libroID="2">
        <titulo>50 Sobras de Grey</titulo>
        <autora>E.L James</autora>
        <paginas>500</paginas>
        <editorial>Anaya</editorial>
        <genero>Romance</genero>
    </libro>
</libros>
